# Warning, do not check out untrusted code with
# the pull_request_target event.
on:
  pull_request_target:
    types: [opened, edited]
name: conventional-release-labels
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@v1
        with:
          type_labels: '{"breaking": "change: breaking", "feat": "change: feat", "perf": "change: perf", "fix": "change: fix", "docs": "change: docs"}'
