name: Publish release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to publish
        required: true
  push:
    tags:
      - "v*.*.*"
jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag && format('refs/tags/{0}', inputs.tag) || github.ref }}
      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          tag_name: ${{ inputs.tag || '' }}
          body: |
            > Please refer to [Changelog]() for all changes.
